### ISSUE TITLE
Fronius Smart Meter support

### ISSUE THREAD

**Issue by SamuelBrucksch** [victronenergy/dbus-fronius#1]
Hi,

thanks for the Fronius support on Victron systems so far. I'm currently getting together all the components I need, so I'm also preparing the software side and was wondering, why there is no native support for the Fronius Smart Meter.

I saw you use the Fronius solar_api here:
[froniussolar_api](https://github.com/victronenergy/dbus-fronius/blob/cf2009cfb5dcf6ac0d7c6f49c421be43a0d82ccd/software/src/froniussolar_api.cpp)

But you do not read the meter data. There is another community project, that reads the meter data instead:
https://github.com/RalfZim/venus.dbus-fronius-smartmeter/blob/master/dbus-fronius-smartmeter.py

Currently the update interval is set to 5s, but it should also be possible to update the smart meter every 1s via http API and use it as system meter instead. 

Do you see any drawbacks by that or any downsides of doing that? What is the update rate of the victron smart meters and would be a recommended update rate?

If i would add fronius smart meter support here and provide the data of it as a meter, could that be used as the default meter for the whole system then?

**Comment by mpvader** [comment]
Hi, having a fronius smart meter in the system, and them the fronius self-controlling and the victron self-controlling leads to instability.

See manuals, there it says you can’t use a fronius meter at all in a victron + fronius system )sorry I can’t remember which manual exactly, most likely Victron/Fronius).

also once a second is slow.

hope that explains it! Good weekend

**Comment by SamuelBrucksch** [comment]
But the Fronius Smart Meter can also be read via ModbusTCP in a faster way. If this is just being used for ESS with a Multiplus-II it should work fine.

**Comment by mpvader** [comment]
Having two systems regulating itself on the same error is a recipe for instability.

sorry but I really don’t see a reason for us to go in this direction. There are meters already, and they work fine.

and in a fronius + victron system there is no need for a fronius smart meter. Even more: you should not install such meter in a fronius + victron system.

**Comment by SamuelBrucksch** [comment]
Thanks for your feedback. Let me describe the setup in more detail, so maybe you understand the reason for this.

In Germany for example you can only feed in 70% of the total PV power (if you install 15kWp only a max of 10.5kW can be fed to the grid) for private PV systems where you partially use the electricity yourself. In summer you sometimes exceed the 70%, still the inverter reduces the power. However if you consume as much power at your home it can exceed the 70% at the inverter, as long as only 70% at max is fed to the grid. That is why many users already install a smart meter when setting up the PV system. Another cause is a wallbox for electric cars, to just charge solar energy. So it is quite common to already install a smart meter with fronius.

Also many people don't install a battery right from the start but later on, as it is still quite expensive. the benefit of Victron as ESS is, that you can install it later on any time, for example if there is a good offer for a battery or you build one yourself.

So in these cases the system already has the smart meter, also depending on your setup you have another meter from the electricity company, another one to measure your self consumption (also from the electricity company for tax reasons on self consumption), so in my case i already have 3 meters installed.

As for an ESS system I do not really understand, what could cause conflicts here. So If Victron already has the values from Fronius, it should be able to use that instead of it's own smart meter, as long as it does not need to control the Fronius Inverter, right?

So couldn't we have these kind of systems:
- Fronius inverter, no fronius smartmeter + victron smartmeter -> victron controls fronius
- Fronius inverter, fronius smartmeter -> victron does not control fronius, but uses values from fronius to control multiplus

There might be other system setups that might not work, but for the below case this seems perfectly fine to me.

**Comment by mpvader** [comment]
If the Fronius controls itself, and the Victron controls itself, there is chance of instability. It will be difficult for us to make it work well in all circumstances, and a change by Fronius to their software might break it again.

and I see some of your points, but the answer remains no: we have other priorities. I have a limited amount of resources and developers.

and having more types of meters means more maintenance and so forth. My opinion is that its not worth our effort. (Even though some systems might benefit)

**Comment by SamuelBrucksch** [comment]
> If the Fronius controls itself, and the Victron controls itself, there is chance of instability. It will be difficult for us to make it work well in all circumstances, and a change by Fronius to their software might break it again.

If you don't mind could you provide a sample where this could cause problems?

I still don't understand the difference where Victron get's the meter readings from. It should not matter if the update frequency is the same if Victron uses the Fronius Meter or the Victron meter in the end. And the Fronius inverter is either configured to be controlled by Victron, or controls itself. But if it is controlled by Victron via Victron smart meter or by Victron via Fronius smart meter seems to be the same to me.

I understand though, that you do not have the capacity to deal with this, however I can help here (if you provide access to the velib so we can actuall ytry this ourself) and I know of some other users that use
https://github.com/RalfZim/venus.dbus-fronius-smartmeter/blob/master/dbus-fronius-smartmeter.py
as a workaround that would be happy to get native support.

I would offer my help to implement this and open a PR.

**Comment by mpvader** [comment]
The cause for instability is that you have two systems (the Fronius and the Victron) trying to keep the power flow in the grid-connection to a certain value. Its like two people in the same car, each having their own pedal, trying to drive at a constant speed together. It won't work well. If it does now, then there is no guarantee that it remains working.

So, its not about where the Victron get its readings from.

Its about having one control loop (Victron system, which controls both Victron and the Fronius PV Inverter), versus two control loops operating independently.

I really can't explain that any better, and I'm really sorry but can't help you.

**Comment by SamuelBrucksch** [comment]
Thanks @mpvader, guess i have to use another workaround then.

Just one final question about this control loop... This should only affect the system, if using the "Zero Feed-in" function, right? Because even with the 70% limit on feed in, the Fronius Inverter will actually not do any limiting on the output or adjust to whatever is consumed (except that it actually allows more power to get into the home grid when more is consumed in my case). So i will not use zero feed in, as i get money for the energy fed to the grid.

So if an ESS system is used, and only a Fronius meter is used and the Multiplus is used to just charge the battery and provide energy, if the inverter does not produce enough energy (or during the night) there shouldn't be any problems, as the only control loop is the one in the Multiplus adjusting to the power values reported from the meter and the inverter is actually not involved at all, right?

**Comment by mpvader** [comment]
Without zero feedin it might indeed work.

And though I don’t like to remain negative: still, for now, its not something we’re insterested in officially supporting. There are enough alternatives that need be kept working properly already.
