### ISSUE TITLE
Link to setup does not exist anymore

### ISSUE THREAD

**Issue by SamuelBrucksch** [victronenergy/dbus-fronius#2]
In the readme there is a link to https://www.victronenergy.com/live/open_source:ccgx:setup_development_environment that does not exist anymore.

**Comment by mpvader** [comment]
Hi thank you! I fixed that, but be warned: you can’t build this repo since you need velib, which is not open source.

**Comment by SamuelBrucksch** [comment]
Thanks, will that be opened at some point so other users can start developing or enhancing functions?

**Comment by mpvader** [comment]
Maybe/probably
