### ISSUE TITLE
Power Limit for SolarEdge

### ISSUE THREAD

**Issue by krpano** [victronenergy/dbus-fronius#4]
Hi,

this a feature request for automatic Power limiting for SolarEdge inverters.

Technically it is possible to send a 0-100 value (16bit) to Modbus address 0xF001 to the SolarEdge Inverter to set the percent of the max. inverter power as limit.

I have tested this and it works very well and quick for me.
No other Modbus commands are required.

With some dynamic control to change that percent value, it should be possible to get to the desired power output...

Or instead of a dynamic control - with an user-input of the max. inverter power (or maybe it is possible to get this information automatically), it would be also possible to limit the exact power in watts from the inverter.

Thanks!

**Comment by mpverrijt** [comment]
I also really wanted this, so got to work on it myself. Luckily we only need a couple of device id defines from velib to compile it ourselves with the SDK.

I made an implementation on my fork and have tested it a bit, it seems to work. It could do with a bit more testing and tweaking of certain settings I guess. You can find it [here](https://github.com/mpverrijt/dbus-fronius) in the solaredge branch. There is also a solaredge-mbs branch for which I made a tool I can used to read and write registers of the solaredge manually via dbus-spy.

**Comment by izak** [comment]
Closing as this is a copy of #6 .
